version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx_host
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${HTTP_PORT}:80
    networks:
      - front
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql_host
    volumes:
      - db-store:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
      - ${DB_PORT}:3306
    networks:
      - back
  nodejs:
    image: node:latest
    container_name: nodejs
    hostname: nodejs_host
    networks:
      - front
      - back
    tty: true
volumes:
  db-store:
networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
  back:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24