import Head from "next/head"
import A_list from "../components/A_list"
import Article from "../components/Article"
import { GetStaticProps } from "next"
import mysql from 'mysql2'

type ArticleProps = React.ComponentProps<typeof Article>
type A_listProps = {
    articles:ArticleProps[]
}

let db = {
    host:'localhost',
    user:'user',
    password:'web',
    database:'web'
}

export default function Home({articles}:A_listProps){
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>

            </header>
            <main>
                <A_list articles={articles}/>
            </main>
            <footer>

            </footer>
        </>
    )
}

export const getStaticProps:GetStaticProps<{articles:ArticleProps[]}> = async (context) => {
    console.log('getstaticprops');
    console.log(context);
    let articles:ArticleProps[] = []
    let connection = mysql.createConnection(db)
    console.log(connection)
    connection.connect()
    connection.query('select * from web',(err,res,fields)=>{
        if (err) throw err
        console.log(res);
        // if (typeof res == 'Array')
        // res.array.forEach(element => {
            
        // });
        // for(let r in res){
        //     console.log(r);
        //     console.log();
        // }
    })
    return {
        props:{
            articles,
        },
    }
}